### ISSUE TITLE
Date in `cache-bust` attribute is not replaced in new app

### ISSUE THREAD

**Issue by thinkh** [phovea/generator-phovea#111]
* Release number or git hash: 87cbd2b8fd79bd09d3b6b83966329f714b8fe513
* OS: Windows 10

### Steps to reproduce

1. Create a new directory
2. `yo phovea`
3. Create web app (client-side only)
4. Install and start the app
5. Open browser

### Observed behavior

`${Date.now}` is not replaced in the all `cache-bust` attributes for Javascript and CSS files.

![grafik](https://user-images.githubusercontent.com/5851088/29206080-a31d5764-7e80-11e7-9775-3cff545b5a8c.png)

As you can see in the screenshot the date is set correctly for the `info` request.

The source can be found here: https://github.com/phovea/generator-phovea/blob/87cbd2b8fd79bd09d3b6b83966329f714b8fe513/generators/init-app/templates/sample_processed/src/index.html

### Expected behavior

* The template variable should be replaced and set dynamically.

**Comment by sgratzl** [comment]
how does your index.ts looks like

**Comment by thinkh** [comment]
The default one:

```typescript
/**
 * Created by Caleydo Team on 31.08.2016.
 */

import 'file-loader?name=index.html!extract-loader?interpolate!html-loader!./index.html';
import 'file-loader?name=404.html-loader!./404.html';
import 'file-loader?name=robots.txt!./robots.txt';
import 'phovea_ui/src/_bootstrap';
import './style.scss';
import {create as createApp} from './app';
import {create as createHeader, AppHeaderLink} from 'phovea_ui/src/header';
import {APP_NAME} from './language';

createHeader(
  <HTMLElement>document.querySelector('#caleydoHeader'),
  { appLink: new AppHeaderLink(APP_NAME) }
);

const parent = document.querySelector('#app');
createApp(parent).init();
```
