### ISSUE TITLE
Add default .gitignore to the init-app 

### ISSUE THREAD

**Issue by thinkh** [phovea/generator-phovea#132]

**Comment by sgratzl** [comment]
init-app is based on _init_web thus should have a `.gitignore` included

**Comment by sgratzl** [comment]
cannot reproduce: 
![greenshot_2017-12-22_14-08-35](https://user-images.githubusercontent.com/4129778/34299194-f040a762-e721-11e7-866b-4dc3f526cfc0.png)

**Comment by NMO13** [comment]
Also in my case, when doing `yo phovea:init-app-slib`, no `.gitignore` gets created.

![image](https://user-images.githubusercontent.com/3988444/34302029-688e449c-e72f-11e7-95c2-36821ea1a82a.png)

**Comment by NMO13** [comment]
Is it possible that the `.gitignore` file get created at the wrong place?
Here I have one:
![image](https://user-images.githubusercontent.com/3988444/34302536-a781354a-e731-11e7-8b56-90d6f43313ff.png)

But here (where .git is) I haven't:

![image](https://user-images.githubusercontent.com/3988444/34302584-dcb83452-e731-11e7-974d-43e02ba75ba5.png)

**Comment by sgratzl** [comment]
reason: https://github.com/npm/npm/issues/1862
