### ISSUE TITLE
yo phovea:init-app-slib throws error

### ISSUE THREAD

**Issue by NMO13** [phovea/generator-phovea#134]
* Release number or git hash: 
* OS: Windows 10

### Steps to reproduce

1. Create empty directory in project
2. Call `yo phovea:init-app-slib`
3. Click through wizard

### Observed behavior
* An error is thrown

### Expected behavior
* slib should be created

Directory structure (yellow highlighted is the folder where the slib should get created) :
![image](https://user-images.githubusercontent.com/3988444/35728287-62a749dc-080b-11e8-92ec-63cec5609991.png)

Error reproduction:

![image](https://user-images.githubusercontent.com/3988444/35677702-f54600aa-0750-11e8-9f87-d573725b34e0.png)

**Comment by sgratzl** [comment]
just to get things right. You want to create a new plugin on top of an existing one? That doesn't work

**Comment by NMO13** [comment]
Ok I thought that an slib is a kind of extension that can be added to an application to have backend support. @thinkh told me that this is not correct. I have updated the quickstart tutorial: https://wiki.datavisyn.io/phovea/additional/quickstart-tutorial
