### ISSUE TITLE
prepare for supporting i18n

### ISSUE THREAD

**Issue by sgratzl** [phovea/generator-phovea#14]
see https://github.com/webpack/webpack/tree/master/examples/i18n

- [ ] wizard option + template files
- [ ] apply option in webpack config to build multiple instances, e.g. a magic `__LANGUAGE__` to copy static language specific file, like `__VERSION__`
- [ ] consider in dist to build multiple tar.gz?

**Comment by sgratzl** [comment]
also possible: https://github.com/Fakundo/jed-webpack-plugin

**Comment by thinkh** [comment]
Related to https://github.com/phovea/phovea_core/issues/154
