### ISSUE TITLE
Support version incrementor for branch properties in phovea_product.json

### ISSUE THREAD

**Issue by thinkh** [phovea/generator-phovea#144]
## Problem

At the moment phovea dependencies are defined with the [minor version incrementor](https://docs.npmjs.com/getting-started/semantic-versioning) (e.g., npm package.json: `"phovea_clue": "^2.0.0"`). However, the `phovea_product.json` contains a hard version number to the git tag `v2.0.0` (e.g., see [gapminder_product](https://github.com/Caleydo/gapminder_product/blob/master/phovea_product.json#L33)).

That could cause potential problems, because npm will use a higher version (e.g., `2.1.3`), but the phovea_product.json will checkout the version `2.0.0`.

## Suggestion

We should support the [npm semver modifier](https://docs.npmjs.com/getting-started/semantic-versioning) for the branch properties in the phovea_product.json.

For the gapminder_product the phovea_product.json would look like this (shortened):

```
[
  {
    "type": "api",
    "label": "gapminder_server",
    "repo": "phovea/phovea_server",
    "branch": "^2.0.0",
    "additional": [
      {
        "name": "phovea_clue",
        "repo": "phovea/phovea_clue",
        "branch": "^2.0.0"
      }
    ]
  }
]
```

**Comment by sgratzl** [comment]
but how should this be resolved? I mean which version should be cloned then?

**Comment by thinkh** [comment]
The same way npm does it. The generator could read all tags, extract the version numbers and then do the version comparison. In case of a `^` the tag with the next highest minor version would be used.

**Comment by thinkh** [comment]
See PR #161

**Comment by thinkh** [comment]
Update the [gapminder_product](https://github.com/Caleydo/gapminder_product/blob/master/package.json#L28) to use master branch again, once this feature is available in master.
