### ISSUE TITLE
option to use product version during build

### ISSUE THREAD

**Issue by sgratzl** [phovea/generator-phovea#148]
so far the package.json version of the main application (e.g. ordino) is used instead of the product version (e.g. ordino_product). Thus even tho there is a new version the shown version won't change since only a dependent plugin of Ordino migh have changed. 

injecting somehow the product version would resolve this issue

**Comment by thinkh** [comment]
Is it the version that is used in the generated buildInfo.json (e.g., https://ordino.caleydoapp.org/buildInfo.json)?

**Comment by sgratzl** [comment]
https://github.com/phovea/generator-phovea/blob/master/generators/_init-web/templates/plain/buildInfo.js#L146

is using the `package.json` -> `.version` field of the main application repo (in this ordino) for computing the `buildInfo.json`. So yes

**Comment by thinkh** [comment]
I implemented an example in https://github.com/Caleydo/ordino_product/pull/15 (requires https://github.com/phovea/generator-phovea/pull/190 and https://github.com/Caleydo/ordino_public/pull/30). 

The only thing left is to update the template files in the generator accordingly and merge PR https://github.com/phovea/generator-phovea/pull/190.

**Comment by anita-steiner** [comment]
can be realized by the injectVersion flag
