### ISSUE TITLE
Dockerfile Maintainer is deprecated

### ISSUE THREAD

**Issue by keckelt** [phovea/generator-phovea#152]
The maintainer instruction in dockerfiles is deprecated: https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

E.g. here: https://github.com/phovea/generator-phovea/blob/master/generators/init-app/templates/processed/deploy/Dockerfile#L3

**Comment by thinkh** [comment]
Thanks for pointing this out. Will be fixed with PR #163.
