### ISSUE TITLE
create JenkinsFile

### ISSUE THREAD

**Issue by sgratzl** [phovea/generator-phovea#16]
see https://jenkins.io/2.0/#pipelines
https://github.com/jenkinsci/pipeline-examples/blob/master/jenkinsfile-examples/nodejs-build-test-deploy-docker-notify/Jenkinsfile
https://jenkins.io/doc/book/pipeline/jenkinsfile/

~ Travis configuration file

**Comment by sgratzl** [comment]
regarding the karma firefox launcher: https://wiki.jenkins-ci.org/display/JENKINS/Xvfb+Plugin

**Comment by sgratzl** [comment]
play with https://hub.docker.com/_/jenkins/ to create a dockerfile for hosting jenkins

**Comment by sgratzl** [comment]
example: https://github.com/Caleydo/lineupjs/blob/master/Jenkinsfile
see also http://stackoverflow.com/questions/40836570/jenkinsfile-and-python-virtualenv

**Comment by sgratzl** [comment]
missing: install firefox: http://tobyho.com/2015/01/09/headless-browser-testing-xvfb/

**Comment by sgratzl** [comment]
missing: python environment

**Comment by sgratzl** [comment]
related #99

**Comment by thinkh** [comment]
Out of scope for now.
