### ISSUE TITLE
CircleCI: Incorrect .tar.gz structure of Python build artifacts

### ISSUE THREAD

**Issue by thinkh** [phovea/generator-phovea#183]
* Release number or git hash: 
* OS: CircleCI and Ubuntu 18.04

### Steps to reproduce

1. Clone [phovea_security_flask](https://github.com/phovea/phovea_security_flask/) (or any other server repo)
2. Install pip dependencies
   * `sudo pip install -r requirements.txt`
   * `sudo pip install -r requirements_dev.txt`
3. `npm run dist` (or for hybrid `npm run dist:python`)
4. Download build artifacts from CircleCI (e.g., [build 52](https://circleci.com/gh/phovea/phovea_security_flask/52#artifacts/containers/0))
5. Compare both .tar.gz files

### Observed behavior

The file structure from can not be published using twine and returns _file could not be opened successfully_. In the following the full error message:

```
/phovea/phovea_security_flask$ twine upload --repository-url https://upload.pypi.org/legacy/ dist/*                                                                                                                                                            Enter your username: caleydo-bot
Enter your password:
Uploading distributions to https://upload.pypi.org/legacy/
Uploading phovea_security_flask-2.3.0-py2.py3-none-any.whl
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 14.2k/14.2k [00:03<00:00, 4.82kB/s]                                                                                                                                              Traceback (most recent call last):
  File "/home/holger/.local/bin/twine", line 11, in <module>
    sys.exit(main())
  File "/home/holger/.local/lib/python3.6/site-packages/twine/__main__.py", line 28, in main
    return dispatch(sys.argv[1:])
  File "/home/holger/.local/lib/python3.6/site-packages/twine/cli.py", line 77, in dispatch
    return main(args.args)
  File "/home/holger/.local/lib/python3.6/site-packages/twine/commands/upload.py", line 127, in main
    return upload(upload_settings, args.dists)
  File "/home/holger/.local/lib/python3.6/site-packages/twine/commands/upload.py", line 68, in upload
    package = PackageFile.from_filename(filename, upload_settings.comment)
  File "/home/holger/.local/lib/python3.6/site-packages/twine/package.py", line 79, in from_filename
    meta = DIST_TYPES[dtype](filename)
  File "/home/holger/.local/lib/python3.6/site-packages/pkginfo/sdist.py", line 13, in __init__
    self.extractMetadata()
  File "/home/holger/.local/lib/python3.6/site-packages/pkginfo/distribution.py", line 108, in extractMetadata
    data = self.read()
  File "/home/holger/.local/lib/python3.6/site-packages/pkginfo/sdist.py", line 40, in read
    archive, names, read_file = self._get_archive(fqn)
  File "/home/holger/.local/lib/python3.6/site-packages/pkginfo/sdist.py", line 26, in _get_archive
    archive = tarfile.TarFile.open(fqn)
  File "/usr/lib/python3.6/tarfile.py", line 1576, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

Looking at the .tar.gz. file it shows that the one from CircleCI is not correct:

**Local Build**

![grafik](https://user-images.githubusercontent.com/5851088/65758260-1688b200-e119-11e9-8826-f05afb444657.png)

**CircleCI Artifact**

![grafik](https://user-images.githubusercontent.com/5851088/65758220-f8bb4d00-e118-11e9-9944-c81904df6ee7.png)

The required _dist_ directory is contained inside the first tar file of the previous screenshot:

![grafik](https://user-images.githubusercontent.com/5851088/65765290-25c32c00-e128-11e9-82ed-a7caf094d84c.png)

### Expected behavior

* The Python build artifact from CircleCI should have the correct file structure.

**Comment by oltionchampari** [comment]
Followed the described steps but in my case the file structure of the circleci and local tar.gz was the same .

**Comment by anita-steiner** [comment]
the where built as expected, so I will close the ticket (by the way: the generator doesn't have artifacts any more - perhaps we should think about that)
