### ISSUE TITLE
Update to Node 12 LTS

### ISSUE THREAD

**Issue by thinkh** [phovea/generator-phovea#191]
Node 12 LTS will be release on 2019-10-22 (see [Node.js](https://nodejs.org/en/about/releases/)). We should update to this version as Node 8 will be outdated by the end of this year (2019-12-31). 

![grafik](https://user-images.githubusercontent.com/5851088/66763999-381fc280-eea9-11e9-850f-424bd378b22e.png)

We need to check, if some dependencies need to be updated as well.

### Checklist

- [x] Install node using [nvm](https://github.com/nvm-sh/nvm): `nvm install 12` on your system
- [x] Test new app (`yo phovea:init-app` then `npm install && npm start`)
- [x] Test new frontend library (`yo phovea:init-lib` then `npm install && npm start`)
- [x] Test new server library (`yo phovea:init-slib` then `npm install && npm start`)
- [x] Test new product (`yo phovea:init-product` then `npm install && npm start`)
- [x] Check if all npm dependencies are working; otherwise update to newer version and update templates accordingly (probably [node-sass](https://www.npmjs.com/package/node-sass?activeTab=versions) must be updated)
- [x] Update CircleCI and Gitlab template files
  - [x] Might require a new version of https://github.com/phovea/phovea_python
  - [x] Might require a new version of https://github.com/phovea/phovea_circleci_python
- [x] Update wiki documentation with new version and nvm installation

### Research

- [x] Check if we can use/add an [_.nvmrc_ file](https://github.com/nvm-sh/nvm#nvmrc) to each project

**Comment by anita-steiner** [comment]
@oltionchampari please test it also with a given product like festival
