### ISSUE TITLE
Remove travis files from templates

### ISSUE THREAD

**Issue by thinkh** [phovea/generator-phovea#192]
Since we are using CircleCI as build environment we can remove travis build files from the templates.

**Comment by thinkh** [comment]
@anita-steiner I would argue to keep the travis build files, but we can just deactivate/not use the travis integration in the github repositories. What do you think?

**Comment by anita-steiner** [comment]
I think we can remove the travis files from all repos, keep the travis files in the generator but don't use them any more

**Comment by thinkh** [comment]
That would mean that existing plugins do not have the the travis file, because we removed it manually, but new plugins do have it. I would just remove it everywhere.
