### ISSUE TITLE
Check generator version on start up

### ISSUE THREAD

**Issue by thinkh** [phovea/generator-phovea#194]
Similar to #162, we should check if there is a newer version of the generator available and print an update message.

We can use https://github.com/yeoman/update-notifier.

![grafik](https://user-images.githubusercontent.com/5851088/66833877-e9336500-ef5c-11e9-99a7-cf2befae0936.png)

```js
const updateNotifier = require('update-notifier');
const pkg = require('./package.json');

updateNotifier({pkg}).notify();
```

**Comment by oltionchampari** [comment]
To test 

- lower the version of the generator-phovea on your local package.json,
- set updateCheckInterval:0
- run` yo phovea`
