### ISSUE TITLE
Update tsconfig.json flags in template files to support i18next library

### ISSUE THREAD

**Issue by oltionchampari** [phovea/generator-phovea#254]
Add the below flags to the tscofig.json templates 

```JSON
 "esModuleInterop": false,
 "allowSyntheticDefaultImports": true
```
The flags are necessary to support the importing  i18next library
see  phovea/phovea_core#159

**Comment by thinkh** [comment]
Here the justification for these flags, copied from the wiki:

Start by adding the following `compilerOptions` flags to the *tsconfig.json* of your plugin (e.g., *pluginName/tsconfig.json*):

```json
  "compilerOptions": {
     // ...
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    // ...
  },
```

*  We are not changing the default value for `esModuleInterop`, but rather set it explicitly see https://www.typescriptlang.org/docs/handbook/compiler-options.html
* `allowSyntheticDefaultImports` is necessary to use i18next and must be set added/enabled in all plugins!
