### ISSUE TITLE
VS Code Python Linting

### ISSUE THREAD

**Issue by keckelt** [phovea/generator-phovea#284]
## Short description

Enable linting of Python code with _flake8_ in VS Code to see linting errors locally.
Linting can be done by the [Python extension for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-python.python).
VS Code can install flake8 for you, however a python installation is required (flake8 is a python package).

Common Python linting errors are:
* Trailing white space
* To many/few blank lines
* Wrong indentation

**Comment by keckelt** [comment]
The default linter of the Python extension is _PyLint_.
This linter was already disabled in our VS Code settings.json template: 
https://github.com/phovea/generator-phovea/blob/4c1a48fbaaf5a95f19bcdbb698fa721a791522ba/generators/workspace/templates/plain/.vscode/settings.json#L18

**Comment by keckelt** [comment]
Documentation for Linting with the Python Extension: https://code.visualstudio.com/docs/python/linting

**Comment by thinkh** [comment]
Released with v3.1.0.
