### ISSUE TITLE
collect plugin versions during build

### ISSUE THREAD

**Issue by sgratzl** [phovea/generator-phovea#30]
where to find the current version / git commit: 

`package.json -> version`

`npm ls --prod --json`

in addition:  
 * cloned modules -> `git rev-parse --verify HEAD`
 * npm modules of repository clone -> `package.json -> "gitHead": ""`

how to inject? -> another define like __version__ ... and put it into bootstrap_fontawesome

**Comment by thinkh** [comment]
Pull request merged.
