### ISSUE TITLE
forEach script with \r entry

### ISSUE THREAD

**Issue by anita-steiner** [phovea/generator-phovea#337]
If you execute .\forEach git pull on Linux (before you execute yo:phovea update that updates the forEach files) you get the following error:

/usr/bin/env: ‘bash\r’: No such file or directory

please remove \r entries in file
see https://stackoverflow.com/questions/29045140/env-bash-r-no-such-file-or-directory

**Comment by anita-steiner** [comment]
with v4.0.0

**Comment by thinkh** [comment]
This is basically an issue with all Linux scripts:

* docker-backup
* docker-compose-debug
* forEach
* withinEnv

We should have a look if specifying the line endings in the _.gitattributes_ solves the problem.

https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings
