### ISSUE TITLE
Update jest to latest version

### ISSUE THREAD

**Issue by dvvanessastoiber** [phovea/generator-phovea#353]
## Observed behavior
* `gulp-jest` (currently at v4.0.3) does not support jest v25 yet, which causes the following error:

![image](https://user-images.githubusercontent.com/52395160/77323991-63d78c00-6d16-11ea-8353-00ceda1e222f.png)

see [gulp issue](https://github.com/aarontrank/gulp-jest/issues/58)

## TODO
* update jest to latest version as soon as possible and fix resulting errors

**Comment by thinkh** [comment]
Waiting for PR https://github.com/aarontrank/gulp-jest/pull/59 to bemerged and published on npm.
