### ISSUE TITLE
Changes for new typescript repos

### ISSUE THREAD

**Issue by anita-steiner** [phovea/generator-phovea#378]
## all hybrids and lib repos

1. .gitignore: 
   * remove /dist/ folder and .map entry
   * changes: 
   ```
    /src/**/*.js
    /tests/**/*.js
    /src/**/*.map
    /tests/**/*.map 
   ```
2. change tsconfig.json:
   ```json
   {
        "compilerOptions": {
	    "module": "ES2020",
	    "target": "ES2019",
	    "importHelpers": true,
	    "sourceMap": true,
	    "declaration": true,
	    "moduleResolution": "node",
	    "jsx": "react",
	    "allowJs": true,
	    "declarationDir": "dist",
	    "outDir": "dist",
	    "experimentalDecorators": true,
	    "noImplicitAny": false,
	    "skipLibCheck": true,
	    "esModuleInterop": false,
	    "resolveJsonModule": true,
	    "allowSyntheticDefaultImports": true
	  },
	  "include": [
	    "src/**/*.ts",
	    "src/**/*.tsx",
	    "tsd.d.ts"
	  ]
   }
   ```
3. remove tsconfig_dev.json
4. change tsd.d.ts:
	```ts	
        //allow sass modules
        declare module "*.scss" {
          const content:string;
          export default content;
        }
        declare module "*.css" {
          const content:string;
          export default content;
        }
        // allow image dependencies
        declare module "*.png";
        declare module "*.jpg";
        declare module "*.gif";
        declare module "*.webp";
        declare module "*.svg";
        //allow html dependencies
        declare module "*.html" {
          const content:string;
          export default content;
        }
        declare module "*.xml" {
          const content:string;
          export default content;
        }
	```
5. remove webpack.config.js and tests.webpack.js
6. remove index.js from root directory
7. change jest.config.js
	```ts
	// test dependencies that require transformation
	let pluginsToTransform = [
	  'tdp_*',
	  'phovea_*',
	  'lineupjs'
	].join('|');
	
	if(pluginsToTransform.length > 0) {
	 /**  Attention: Negative Lookahead! This regex adds the specified repos to a whitelist that holds plugins that are excluded from the transformIgnorePatterns.
	  * This means that pluginsToTransform should contain all repos that export ts files. They can only be handled by the transformation. */
	    pluginsToTransform = `(?!${pluginsToTransform})`;
	}
	
	/**
	 * TODO check if we can process inline webpack loaders (e.g. as found in https://github.com/phovea/phovea_ui/blob/master/src/_bootstrap.ts)
	 * see also https://jestjs.io/docs/en/webpack#mocking-css-modules
	 */
	module.exports = {
	  transform: {
	    "^.+\\.(js|ts|tsx)$": "ts-jest",
	    "\\.xml$": "jest-raw-loader"
	  },
	  testRegex: "(.*(test|spec))\\.(tsx?)$",
	  moduleFileExtensions: [
	    "ts",
	    "tsx",
	    "js",
	    "jsx",
	    "json",
	    "node"
	  ],
	  modulePaths: [
	    "src"
	  ],
	  transformIgnorePatterns: [`../node_modules/${pluginsToTransform}`, `node_modules/${pluginsToTransform}`],
	  globals: {
	    // has to be set to true, otherwise i18n import fails
	    "ts-jest": {
	      "tsConfig": {
	        "esModuleInterop": true
	      }
	    }
	  },
	  moduleNameMapper: {
	    "^.+\\.(css|less|scss|sass|png|jpg|gif|svg)$": "identity-obj-proxy"
	  }
	}
	```
8. change package.json:
   - add / change the following entries:
      ```json
	  "main": "dist/index.js",
	  "types": "dist/index.d.ts",
      ```
   - for files array the following entries are necessary for typescript:
	   ```js
		  "files": [
		    "src",
		    "phovea_registry.js",
		    "dist"
		  ]
	   ```
   - change/add the following npm scripts:
	   ```json
		"posttest": "npm run lint",
		"clean": "rimraf dist lib && npm run clean:compile",
		"clean:compile": "rimraf src/**/*.map src/**/*.js src/**/*.d.ts tests/**/*.js tests/**/*.map tests/**/*.d.ts demo/**/*.js demo/**/*.map demo/**/*.d.ts",
		"compile:watch": "tsc -w",
		"build": "npm run clean && npm run compile && npm run copy",
		"copy": "npm run copy-assets && npm run copy-styles",
		"copy-assets": "if [ -d src/assets ]; then shx --verbose cp -R src/assets/. dist/assets/; fi",
		"copy-styles": "if [ -d src/scss ]; then shx --verbose cp -R src/scss/. dist/scss/; fi",
		"dist": "mkdir lib && cd dist && tar cvzf ../lib/<NAME>.tar.gz *"
	   ```
     -- or (for hybrid)
	   ```json
		"posttest:web": "npm run lint",
		"clean": "rimraf dist lib && npm run clean:compile",
		"clean:compile": "rimraf src/**/*.map src/**/*.js src/**/*.d.ts tests/**/*.js tests/**/*.map tests/**/*.d.ts demo/**/*.js demo/**/*.map demo/**/*.d.ts",
		"compile:watch": "tsc -w",
		"build:web": "npm run clean && npm run compile && npm run copy",
		"copy": "npm run copy-assets && npm run copy-styles",
		"copy-assets": "if [ -d src/assets ]; then shx --verbose cp -R src/assets/. dist/assets/; fi && if [ -d src/templates ]; then shx --verbose cp -R src/templates/. dist/templates/; fi",
		"copy-styles": "if [ -d src/scss ]; then shx --verbose cp -R src/scss/. dist/scss/; fi",
		"dist:web": "mkdir lib && cd dist && tar cvzf ../lib/<NAME>.tar.gz *"
	   ```

   - remove the following npm scripts: `pretest` (or `pretest:web` for hybrid), `build:dev`, `start`, `start:hot`, `watch`
   - remove the following `devDependencies`:
	  - all `*-loader` packages except `jest-raw-loader`
	  - all `*-plugin` packages
	  - all `webpack*` packages
	  - `node-sass`
   - add the following `devDependencies`:
	  - "rimraf": "^3.0.0",
	  - "shx": "^0.3.2",

9. make phovea.js in root folder to phovea.ts in src folder

10. change phovea_registry.js
	```ts
	import {PluginRegistry} from 'phovea_core';
	import reg from './dist/phovea';
	....
	PluginRegistry.getInstance().register(<NAME>,reg);
	```
11. remove tests.webpack.js

## Only for `app` repos

For apps, we need the following additional changes (to the ones described above):

1. npm scripts in package.json:
   - add: `"copy-app-assets": "shx --verbose cp src/*.txt dist/ | true && shx --verbose cp src/*.html dist/ | true && shx --verbose cp src/*.ejs dist/ | true"`,
   - add: 	`"copy": "npm run copy-assets && npm run copy-styles && npm run copy-app-assets"`
   - change: `"build": "npm run clean && npm run compile && npm run copy",`
   - change: `"dist": "mkdir lib && cd dist && tar cvzf ../lib/<NAME>.tar.gz *",`
2. rename src/index.html to src/index.template.ejs

**Comment by thinkh** [comment]
@anita-steiner Why do we need the `madge` package? Where is it used?

**Comment by anita-steiner** [comment]
for apps, we need the following additional changes:
1. npm scripts in package.json:
- add: "copy-app-assets": "cp src/*.txt dist/ && cp src/*.html dist/ && cp src/*.ejs dist/",
- change: "build": "npm run clean && npm run compile && npm run copy-assets && npm run copy-styles && npm run copy-app-assets",
- change: "dist": "mkdir lib && cd dist && tar cvzf ../lib/<NAME>.tar.gz *",

2. rename src/index.html to src/index.template.ejs

**Comment by keckelt** [comment]
> 1. .gitignore: 
>    * remove /dist/ folder and .map entry
>    * changes: 
>    ```
>     /src/**/*.js
>     /tests/**/*.js
>     /src/**/*.map
>     /tests/**/*.map 
>    ```


Does that mean replace `*.map` with a `/src/**/*.map` and `/tests/**/*.map`?

**Comment by keckelt** [comment]
Is it on purpose that the clean command here is different from the one in the package templates: https://github.com/phovea/generator-phovea/blob/develop/generators/_init-web/templates/package.tmpl.json

**Comment by keckelt** [comment]
`copy-app_assets` is also different in the templates (missing `*` at .txt and .html):
* https://github.com/phovea/generator-phovea/blob/develop/generators/init-app/templates/package.tmpl.json
* https://github.com/phovea/generator-phovea/blob/develop/generators/init-app-slib/templates/package.tmpl.json

**Comment by keckelt** [comment]
I'm also still having karma/jasmine in the repo.
I've removed the entries in package json and add the jest config.

Do i have to replace the app.test.ts file that with some jest thing? 
```
/// <reference types="jasmine" />
// import {create} from '../src/app';

// describe('create', () => {
//   it('is method', () => {
//     expect(typeof create).toEqual('function');
//   });
// });

```
