### ISSUE TITLE
Error running `yo phovea:add-extension`

### ISSUE THREAD

**Issue by thinkh** [phovea/generator-phovea#38]
* Release number or git hash: https://github.com/phovea/generator-phovea/commit/c6cd1ab22eabecb6a542bd015bf78c0863931ff7
* Web browser version and OS: Windows
* Environment (local or deployed): Local

### Steps to reproduce

1. Check out the migrate branch of the [TaCo repo](https://github.com/Caleydo/taco.git) 
2. Open command line and run `D:\dev\repos\phovea\taco>yo phovea:add-extension`
3. Answer the following questions:
```
? Type tacoView
? ID Histogram2D
? File Name ./src/histogram_2d
? Extras (key=value) Press <enter> to launch your preferred editor.
```
4. The only way to continue is to enter and the Windows Editor opens. After entering some or none values, saving the file and closing the editor I recieve the following error message on the console:

```
? Extras (key=value) Received
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'trim' of undefined
    at text.split.forEach (D:\dev\repos\phovea\generator-phovea\generators\add-extension\index.js:12:18)
    at Array.forEach (native)
    at toJSONFromText (D:\dev\repos\phovea\generator-phovea\generators\add-extension\index.js:10:20)
    at prompt.then (D:\dev\repos\phovea\generator-phovea\generators\add-extension\index.js:72:17)
```

### Observed behavior
* Any unexpected output or action (or lack of expected output or action)
* Web browser console errors (including tracebacks)
* Server errors (relevant messages and tracebacks)
* Static or animated images showing the UI behavior

### Expected behavior
* No error message and added information to the phovea files.

**Comment by thinkh** [comment]
It seems that the error only occurs when using the default windows command line. When using the Git Bash the generator works. However, then the entered content is duplicated (which is not a severe bug).

![phovea_add-extension](https://cloud.githubusercontent.com/assets/5851088/20710935/424fd4fe-b63d-11e6-83d1-eee3ee142aad.png)

**Comment by sgratzl** [comment]
`yeoman` uses https://github.com/SBoudrias/Inquirer.js internally for prompting. All the reported compatibility issues are related to this library that is given.

**Comment by thinkh** [comment]
Ok, thanks for clarifying.
