### ISSUE TITLE
Allow overwriting of generated workspace docker-compose.yml

### ISSUE THREAD

**Issue by oltionchampari** [phovea/generator-phovea#385]
## Short description

Currently `yo phovea:setup-workspace` generates a `docker-compose.yml ` in the workspace by merging all `docker-compose-partial.yml` files of the individual plugins.

We would like to create in each product repo a `docker-compose.yml` file which overwrites the generated one.

Also we would like the `build.js` file to consider the `docker-compose.yml`  file from the product repo, if present, and overwrite the generated one

Hint: Use the label in the `phovea-product.json` as name for the services.

**Comment by keckelt** [comment]
Are the product's files present locally atm?

**Comment by oltionchampari** [comment]
> Are the product's files present locally atm?

@keckelt  I don't quite understand your question, which files are you interested in exactly? The product's repository `docker-compose.yml`? Atm it does not yet exist.

**Comment by keckelt** [comment]
Sorry, i confused something :) 
Shouldn't have looked into it so late yesterday 😊

**Comment by oltionchampari** [comment]
### Update
Implementation hint: Modify `buildDockerImage()` fucntion to use Dockerfile in product repository
Files structure should be:
* `docker/docker_web/Dockerfile`
* `docker/docker_server/Dockerfile`
