### ISSUE TITLE
Product build ignores `--injectVersion` flag

### ISSUE THREAD

**Issue by thinkh** [phovea/generator-phovea#405]
* Release number or git hash: v6.0.0
* OS: Linux
* Environment (local or deployed): Both

### Steps to reproduce

1. [ordino_product package.json is set to `7.0.0`](https://github.com/Caleydo/ordino_product/blob/c0460c8d0a9b0b1a8dd85d607d052eb6ded2c06a/package.json#L5)
2. [`--injectVersion` flag is set in circleci/config.yml](https://github.com/Caleydo/ordino_product/blob/c0460c8d0a9b0b1a8dd85d607d052eb6ded2c06a/.circleci/config.yml#L61)

### Observed behavior

![grafik](https://user-images.githubusercontent.com/5851088/90242379-35755d00-de2d-11ea-9254-811e2a1acd17.png)

The final build has the [version `8.0.0` of the app repository ordino_public](https://github.com/Caleydo/ordino_public/blob/d141893703642ad4a09e5521435a3e6a72379a13/package.json#L5).

### Expected behavior

The final build should use the product version `7.0.0`

**Comment by thinkh** [comment]
I just saw in the _bug report_ dialog that the correct version number is available from the workspace package.json.

![grafik](https://user-images.githubusercontent.com/5851088/90242721-d06e3700-de2d-11ea-88b6-3c87b748540b.png)

Other things I noticed:

* The application name is incorrect and should be overriden with the name of the product package.json
* The version number from the workspace package-lock.json for cloned repositories is not stated

**Comment by anita-steiner** [comment]
@thinkh what do you mean with not stated

in reality it should be possible (in the future) that you add your package.json and package-lock.json in your templates folder

**Comment by thinkh** [comment]
> @thinkh what do you mean with not stated
> 
> in reality it should be possible (in the future) that you add your package.json and package-lock.json in your templates folder

In the screenshot above:

```json 
"ordino": {
  "version": "file:ordino"
}
```

The the current package.json from the workspace does not help either, as it has a relative path:

```json
"dependencies": {
  "ordino": "./ordino"
}
```

This problem willl only be solved, if we have real version numbers again.
