### ISSUE TITLE
Switch from node-sass to Dart Sass

### ISSUE THREAD

**Issue by thinkh** [phovea/generator-phovea#438]
The npm package [node-sass is deprecated](https://github.com/sass/node-sass#node-sass) and should be replaced with Dart Sass:

> Warning: LibSass and Node Sass are deprecated. While they will continue to receive maintenance releases indefinitely, there are no plans to add additional features or compatibility with any new CSS or Sass features. Projects that still use it should move onto Dart Sass.

Dart should be mostly compatible and offers even new features such as [`@use`](https://sass-lang.com/documentation/at-rules/use).

> Dart Sass is the primary implementation of Sass, which means it gets new features before any other implementation. It's fast, easy to install, and it compiles to pure JavaScript which makes it easy to integrate into modern web development workflows.

Updating can be done in two simple steps:

1. `npm uninstall node-sass`
2. `npm i -D sass`

**Comment by anita-steiner** [comment]
see https://github.com/phovea/generator-phovea/tree/asteiner/dart_sass

**Comment by anita-steiner** [comment]
there are some warnings like 
Deprecation Warning: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(3em, 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

  ╷
7 │   line-height: (3em / 4);

**Comment by keckelt** [comment]
FYI: We are successfully building Coral with dart now for a month or so (using Holger's branch)
