### ISSUE TITLE
Change query for github "use SSH (Y/M)" to "use SSH (S) or use HTTPS (H)"

### ISSUE THREAD

**Issue by alexsb** [phovea/generator-phovea#82]
When running 

```
yo phovea:setup-workspace XX_product
```

One is first queried to use SSH for github with a Y/N flag. This can be confusing (it was for me) as people might not be aware of the implied alternative "N". 

It might be better to instead ask for: 
```
To access GitHub, use HTTPS (H) or use SSH (S)
```

I'd also put HTTPS first, as it's probably more common and avoids extra steps for potential users.

**Comment by sgratzl** [comment]
it is a yes no question by default it is No

**Comment by alexsb** [comment]
Then at least tell us what Yes means.

**Comment by anita-steiner** [comment]
It checks this with "SSH clone" --> yes/no
