### ISSUE TITLE
Conflict when setting up a product from scratch

### ISSUE THREAD

**Issue by alexsb** [phovea/generator-phovea#83]
When setting up a product from scratch, I get the following conflict: 

```
conflict lineage/.idea/workspace.xml
? Overwrite lineage/.idea/workspace.xml? overwrite
    force lineage/.idea/workspace.xml
```

I suspect that's because the workspace is both available in the server and the client repository? 

This probably doesn't matter much, but it's not obvious for someone new to the thing how to react. Can this be avoided?

**Comment by sgratzl** [comment]
current code uses a different approach for generating run configurations, so should be fixed
