### ISSUE TITLE
Help installation

### ISSUE THREAD

**Issue by drii-cavalcanti** [phovea/generator-phovea#85]
* Release number or git hash: 
* OS: Fedora
![image](https://cloud.githubusercontent.com/assets/20502108/24280713/8d827154-1031-11e7-8ee6-4380d1009452.png)

Can you help?

**Comment by sgratzl** [comment]
can you elaborate how you created the application and maybe host the code somewhere such that I can take a look at it?

**Comment by DriiCavalcanti** [comment]
I did it:
1.
![image](https://cloud.githubusercontent.com/assets/20502108/24317072/ceda0134-10d2-11e7-87cd-59f0b36609a8.png)
2. **NPM INSTALL**: No error
    Just Warning: 'npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):'
   and: 'npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})'

3. **NPM START**

So I got the following errors:
     [at-loader] Checking finished with 11 errors
     Hash: 0dfbe2186613b4628cb5
     Version: webpack 2.2.1
     Time: 152912ms
![image](https://cloud.githubusercontent.com/assets/20502108/24317429/ac4d8a34-10d5-11e7-9b2e-f76fa66f782b.png)
and
    [at-loader] Checking finished with 11 errors
    Hash: e7222edde858b1c6e235
    Version: webpack 2.2.1
    Time: 26206ms
![image](https://cloud.githubusercontent.com/assets/20502108/24317450/e156b552-10d5-11e7-89af-62ab64696985.png)

I deleted two folders (phovea_generator/node_modules/phovea_importer and phovea_generator/node_modules/phovea_vis_lineup).
**So I got the error n console:**
ERROR in ./phovea_registry.js
Module not found: Error: Can't resolve 'phovea_importer/phovea_registry.js' in '.../phovea_generator'
 @ ./phovea_registry.js 17:0-44
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./phovea_registry.js file-loader?name=buildInfo.json!/tmp/buildInfoeglul3di.txt file-loader?name=phoveaMetaData.json!/tmp/metaDatahyxk1emi.txt ./src/index.ts

ERROR in ./phovea_registry.js
Module not found: Error: Can't resolve 'phovea_vis_lineup/phovea_registry.js' in '/home/Drii/projects/CALEYDO/phovea_generator'
 @ ./phovea_registry.js 18:0-46
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./phovea_registry.js file-loader?name=buildInfo.json!/tmp/buildInfoeglul3di.txt file-loader?name=phoveaMetaData.json!/tmp/metaDatahyxk1emi.txt ./src/index.ts

## you can see my code [here](https://www.dropbox.com/sh/725eq178ccp0xcc/AAAnPcdb9pn2GtfN-inbaIV-a?dl=0)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
NPM VERSION: 3.10.10
NODE VERSION: v6.10.0

LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 25 (Twenty Five)
Release:	25
Codename:	TwentyFive
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Linux dri-pc 4.9.12-200.fc25.x86_64 #1 SMP Thu Feb 23 19:31:49 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Thank you for your attention to this matter!
